/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tutorial_estructura_datos_umg.v1;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lennyn
 */
public class Login extends javax.swing.JFrame {
Conexion conexion;
String Datos[]; 
String Nombre,correo;
ImageIcon foto=null;
boolean entrar= false;/**
     * Creates new form Login
     */
    public Login() {
        
    
        initComponents();
            setLocationRelativeTo(null);
            
       ImageIcon Fondo = new ImageIcon("Fondo.jpg");     
       ImageIcon User = new ImageIcon("User.png");     
       ImageIcon Password = new ImageIcon("Password.png");     
       ImageIcon Usuario = new ImageIcon("Usuario.png");     
       
       
       jLabel1.setIcon(Fondo);
       jLabel2.setIcon(Usuario);
        jLabel3.setIcon(Password);
         jLabel4.setIcon(User);
         
    }


    public void setjTextField(String jTextField) {
        this.jTextField1.setText(jTextField);
        this.jLabel2.setVisible(false);
    }

    public void setjPasswordField1(String jp) {
        this.jPasswordField1.setText(jp);
        this.jLabel3.setVisible(false);
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 160, 50));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 140));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        jLabel3.setEnabled(false);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 320, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel2.setText("USUARIO");
        jLabel2.setEnabled(false);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton2.setText("CREAR USUARIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 190, -1));

        jPasswordField1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, 50));

        jTextField1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 50));

        jButton3.setBackground(new java.awt.Color(255, 51, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setText("Leer QR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 160, 40));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
      jLabel2.setVisible(false);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
    NuevoUsuario Nuevo = new NuevoUsuario();
Nuevo.setVisible(true);
this.dispose();
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
String Usuario = "";
String contraseña =""; 
    




    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       conexion  = new Conexion();
      Connection connection = conexion.getConnection();   
      
     Usuario = jTextField1.getText();     
         contraseña = "";
       for (int i = 0; i < jPasswordField1.getPassword().length; i++) {
            contraseña += jPasswordField1.getPassword()[i];
       } 
       
       String codigo = GenerarCodigo();

Datos = new String[]{Usuario,contraseña,codigo};
       
     conexion.leerDato(Datos);
     
     
       Nombre = conexion.getNombre();
       correo = conexion.getCorreo();
       entrar = conexion.isEntrar();
     
       
        if (entrar==true) {
          String input = JOptionPane.showInputDialog("Ingrese el token enviado a"+correo);       
      if(Integer.parseInt(codigo) == Integer.parseInt(input) ){
          Menu menu = new Menu((ImageIcon) this.jLabel4.getIcon(),Nombre.toUpperCase());
                         JOptionPane.showMessageDialog(null, "BIENVENIDO "+Nombre.toUpperCase());
                         menu.setVisible(true);
                        dispose();
                        // aqui se llama al programa despues de logearse
                        } else{JOptionPane.showMessageDialog(this, "Codigo de confirmación incorrecto");  
      
      this.jTextField1.setText("");
      this.jPasswordField1.setText("");
      this.jLabel2.setVisible(true);
      this.jLabel3.setVisible(true);
      
      }    
        }
   


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
LeerQR lq = new LeerQR();
lq.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        conexion  = new Conexion();
      Connection connection = conexion.getConnection();   
    try {
        setFoto(conexion.buscarFoto(jTextField1.getText()));
        jLabel4.setIcon(getFoto());
        jLabel4.setIcon((new ImageIcon(foto.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH))));
        jLabel4.updateUI();
    } catch (IOException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jPasswordField1MouseClicked


    
    
    
    
    
    
    
   private String GenerarCodigo(){
   
   int Valor =(int)(Math.random()*100000 +100000);
                            System.out.println(Valor);  
   
   String codigo = String.valueOf(Valor);
    return codigo;
   
   } 
    

    
    String usuario = "Users.txt";
private String[] datos= null;

int token = 123456;

boolean correcto = false; 
 public void leer() {
        String contenido, clave, user;
    
        try {
            FileReader lectura = new FileReader(usuario);
            BufferedReader lector = new BufferedReader(lectura);
            contenido = lector.readLine();
            while (contenido != null) {
                try {
                    contenido = lector.readLine();
                    datos = contenido.split(",");
                    clave = datos[4];
                    user =  datos[2];

                    if ((Usuario.equals(user)) && (contraseña.equals(clave))) {
                       
                          
                       correcto = true;
                        contenido= null;
                        String correo="lariy68584@lockaya.com";//lariy68584@lockaya.com
                        
                        ///hacer consulta del correo 
                          int Valor =(int)(Math.random()*100000 +100000);
                            System.out.println(Valor);  
                            
                         /// llamart metodo de keidy enviar correo y Valor   
                         
                     Correo Correo = new Correo();
                     Correo.ejecutarCorreo(String.valueOf(Valor), correo); 
                       String input = JOptionPane.showInputDialog("Ingrese el token enviado a "+correo);

                        if(Valor == Integer.parseInt(input) ){
                         JOptionPane.showMessageDialog(null, "BIENVENIDO "+user.toUpperCase());
//                        Arbol buscar = new Arbol();
//                       buscar.setVisible(true);
                      //  buscar.obtenerDatos(correo,datos[3]);
                      
                        dispose();
                        } else{JOptionPane.showMessageDialog(this, "no sea imbecil y escriba bien esa su mierda");    }                                       
//                        
                    }else{correcto = false;}

                } catch (Exception e) {
                    System.out.println("Error. " + e);
                }
            }
           // JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecta ");
        } catch (FileNotFoundException ex) {
            System.out.println("erro> " + ex);
        } catch (IOException ex) {
            System.out.println("erro> " + ex);
        }
        
        if (correcto ==false) {
         JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecta ");
     }
        
    }

    public ImageIcon getFoto() {
        jLabel4.setIcon((new ImageIcon(foto.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH))));
        return foto;
    }

    public void setFoto(ImageIcon foto) {
        this.foto = foto;
    }
    
   
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
